# DO NOT PUT THIS FILE IN A REPOSITORY
[Secrets]
# Set these to string values if you wish to protect your scoring application with authentication
# Examples:
# basic_auth_username = "Team2584"
# basic_auth_password = "4theW1n"
basic_auth_username = false
basic_auth_password = false

# Required for this app to work.  Don't worry, API access is free
# see: https://frc-events.firstinspires.org/services/api/register
FRC_Events_API_Username = "sampleuser"
FRC_Events_API_Auth_Token = "7eaa6338-a097-4221-ac04-b6120fcc4d49"