# If you want to enable automatic loading of team and match data for event use this section
# You can also manually load this data.  Check the load_data command for more information
# Leaving these as false below will result in a warning if the team and match information 
# is not loaded in the db and you use the "run" command

# The initialize command placed the following file in the root of your home directory
# Please check that file for further instructions
# DO NOT INCLUDE THIS SECRETS FILE IN YOUR REPOSITORY
[Secrets]
secrets_file = "~/.RCSA_SECRETS.toml"

[FRCEvents]
# Provide path to the file holding your FRC Events API Key here
# This file should only contain the API key in Base64 encoding as shown at: https://frc-api-docs.firstinspires.org/?version=216cd832-1976-40b0-855b-3a4d92166c08#authorization
# Example: echo -n "sampleuser:7eaa6338-a097-4221-ac04-b6120fcc4d49" | base64 > ~/.FRCEVENTSAPI
# DO NOT include this file in your repository!!
APIKey_File = "~/.FRCEVENTSAPI"

# Place the event ID you are scoring here.
first_event_id = false
# If you know your district code, place it here to get faster results from First Events
district_id = false
URL_Root = "https://frc-api.firstinspires.org/v3.0/"

# By default the server is only configured to run locally for testing
# You will need to replace this IP_Address with 0.0.0.0 (or other public interface) to make this publicly available
# Failure to change the IP when using "run" command will result in a warning
[ServerConfig]
IP_Address = "127.0.0.1"
port = 8080
# These will be set automatically when using "initialize" command
user_static_folder = false
scoring_database = false
log_filename = false
# This must be "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
# See: https://docs.python.org/3/library/logging.html#levels
log_level = "INFO"
scoring_page = "scoring.html"
# If you know the domain of your server put it here.  Not necessary but helps with providing a URL to the team
FQDN = "localhost"



